source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!
workspace 'app-obj-c'

target 'app-obj-c' do
    pod 'AffiseAttributionLib', :path => '../../'
    pod 'AffiseSKAdNetwork', :path => '../../'
    pod 'AffiseInternal', :path => '../../'
    pod 'AffiseModule', :path => '../../'
end
